"""Adding the base hero/item/skill data.

Revision ID: 102ca43c892f
Revises: 19ba0bf28501
Create Date: 2011-12-31 22:34:02.694543

"""

# downgrade revision identifier, used by Alembic.
down_revision = '19ba0bf28501'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # Base Items
    op.bulk_insert('items',
        [
            {'name':, 'vendor':, 'cost':, 'image_name':, 'resource_name':, 'hon_name':, 'order':, 'agility':None, 'strength':None, 'intelligence':None, 'all':None, 'armor':None, 'damage':None, 'selected_attribute':None, 'mana':None, 'health':None, 'hp_regeneration':None, 'hp_regeneration_percentage':None, 'mana_regeneration':None, 'mana_regeneration_percentage':None, 'attack_speed':None, 'attack_speed_percentage':None, 'evasion':None, 'evasion_percentage':None, 'movement_speed':None, 'movement_speed_percentage':None, 'cooldown':None, 'mana_cost':None, 'tier':1, 'parent_id':None, 'description':None, 'active':None, 'passive':None, 'use':None, 'sub_description':None},
            {'name':, 'vendor':, 'cost':, 'image_name':, 'resource_name':, 'hon_name':, 'order':, 'agility':None, 'strength':None, 'intelligence':None, 'all':None, 'armor':None, 'damage':None, 'selected_attribute':None, 'mana':None, 'health':None, 'hp_regeneration':None, 'hp_regeneration_percentage':None, 'mana_regeneration':None, 'mana_regeneration_percentage':None, 'attack_speed':None, 'attack_speed_percentage':None, 'evasion':None, 'evasion_percentage':None, 'movement_speed':None, 'movement_speed_percentage':None, 'cooldown':None, 'mana_cost':None, 'tier':1, 'parent_id':None, 'description':None, 'active':None, 'passive':None, 'use':None, 'sub_description':None},
            {'name':, 'vendor':, 'cost':, 'image_name':, 'resource_name':, 'hon_name':, 'order':, 'agility':None, 'strength':None, 'intelligence':None, 'all':None, 'armor':None, 'damage':None, 'selected_attribute':None, 'mana':None, 'health':None, 'hp_regeneration':None, 'hp_regeneration_percentage':None, 'mana_regeneration':None, 'mana_regeneration_percentage':None, 'attack_speed':None, 'attack_speed_percentage':None, 'evasion':None, 'evasion_percentage':None, 'movement_speed':None, 'movement_speed_percentage':None, 'cooldown':None, 'mana_cost':None, 'tier':1, 'parent_id':None, 'description':None, 'active':None, 'passive':None, 'use':None, 'sub_description':None},
            {'name':, 'vendor':, 'cost':, 'image_name':, 'resource_name':, 'hon_name':, 'order':, 'agility':None, 'strength':None, 'intelligence':None, 'all':None, 'armor':None, 'damage':None, 'selected_attribute':None, 'mana':None, 'health':None, 'hp_regeneration':None, 'hp_regeneration_percentage':None, 'mana_regeneration':None, 'mana_regeneration_percentage':None, 'attack_speed':None, 'attack_speed_percentage':None, 'evasion':None, 'evasion_percentage':None, 'movement_speed':None, 'movement_speed_percentage':None, 'cooldown':None, 'mana_cost':None, 'tier':1, 'parent_id':None, 'description':None, 'active':None, 'passive':None, 'use':None, 'sub_description':None},
            {'name':, 'vendor':, 'cost':, 'image_name':, 'resource_name':, 'hon_name':, 'order':, 'agility':None, 'strength':None, 'intelligence':None, 'all':None, 'armor':None, 'damage':None, 'selected_attribute':None, 'mana':None, 'health':None, 'hp_regeneration':None, 'hp_regeneration_percentage':None, 'mana_regeneration':None, 'mana_regeneration_percentage':None, 'attack_speed':None, 'attack_speed_percentage':None, 'evasion':None, 'evasion_percentage':None, 'movement_speed':None, 'movement_speed_percentage':None, 'cooldown':None, 'mana_cost':None, 'tier':1, 'parent_id':None, 'description':None, 'active':None, 'passive':None, 'use':None, 'sub_description':None},
            {'name':, 'vendor':, 'cost':, 'image_name':, 'resource_name':, 'hon_name':, 'order':, 'agility':None, 'strength':None, 'intelligence':None, 'all':None, 'armor':None, 'damage':None, 'selected_attribute':None, 'mana':None, 'health':None, 'hp_regeneration':None, 'hp_regeneration_percentage':None, 'mana_regeneration':None, 'mana_regeneration_percentage':None, 'attack_speed':None, 'attack_speed_percentage':None, 'evasion':None, 'evasion_percentage':None, 'movement_speed':None, 'movement_speed_percentage':None, 'cooldown':None, 'mana_cost':None, 'tier':1, 'parent_id':None, 'description':None, 'active':None, 'passive':None, 'use':None, 'sub_description':None},
            {'name':, 'vendor':, 'cost':, 'image_name':, 'resource_name':, 'hon_name':, 'order':, 'agility':None, 'strength':None, 'intelligence':None, 'all':None, 'armor':None, 'damage':None, 'selected_attribute':None, 'mana':None, 'health':None, 'hp_regeneration':None, 'hp_regeneration_percentage':None, 'mana_regeneration':None, 'mana_regeneration_percentage':None, 'attack_speed':None, 'attack_speed_percentage':None, 'evasion':None, 'evasion_percentage':None, 'movement_speed':None, 'movement_speed_percentage':None, 'cooldown':None, 'mana_cost':None, 'tier':1, 'parent_id':None, 'description':None, 'active':None, 'passive':None, 'use':None, 'sub_description':None},
            {'name':, 'vendor':, 'cost':, 'image_name':, 'resource_name':, 'hon_name':, 'order':, 'agility':None, 'strength':None, 'intelligence':None, 'all':None, 'armor':None, 'damage':None, 'selected_attribute':None, 'mana':None, 'health':None, 'hp_regeneration':None, 'hp_regeneration_percentage':None, 'mana_regeneration':None, 'mana_regeneration_percentage':None, 'attack_speed':None, 'attack_speed_percentage':None, 'evasion':None, 'evasion_percentage':None, 'movement_speed':None, 'movement_speed_percentage':None, 'cooldown':None, 'mana_cost':None, 'tier':1, 'parent_id':None, 'description':None, 'active':None, 'passive':None, 'use':None, 'sub_description':None},
            {'name':, 'vendor':, 'cost':, 'image_name':, 'resource_name':, 'hon_name':, 'order':, 'agility':None, 'strength':None, 'intelligence':None, 'all':None, 'armor':None, 'damage':None, 'selected_attribute':None, 'mana':None, 'health':None, 'hp_regeneration':None, 'hp_regeneration_percentage':None, 'mana_regeneration':None, 'mana_regeneration_percentage':None, 'attack_speed':None, 'attack_speed_percentage':None, 'evasion':None, 'evasion_percentage':None, 'movement_speed':None, 'movement_speed_percentage':None, 'cooldown':None, 'mana_cost':None, 'tier':1, 'parent_id':None, 'description':None, 'active':None, 'passive':None, 'use':None, 'sub_description':None},
            {'name':, 'vendor':, 'cost':, 'image_name':, 'resource_name':, 'hon_name':, 'order':, 'agility':None, 'strength':None, 'intelligence':None, 'all':None, 'armor':None, 'damage':None, 'selected_attribute':None, 'mana':None, 'health':None, 'hp_regeneration':None, 'hp_regeneration_percentage':None, 'mana_regeneration':None, 'mana_regeneration_percentage':None, 'attack_speed':None, 'attack_speed_percentage':None, 'evasion':None, 'evasion_percentage':None, 'movement_speed':None, 'movement_speed_percentage':None, 'cooldown':None, 'mana_cost':None, 'tier':1, 'parent_id':None, 'description':None, 'active':None, 'passive':None, 'use':None, 'sub_description':None},
            {'name':, 'vendor':, 'cost':, 'image_name':, 'resource_name':, 'hon_name':, 'order':, 'agility':None, 'strength':None, 'intelligence':None, 'all':None, 'armor':None, 'damage':None, 'selected_attribute':None, 'mana':None, 'health':None, 'hp_regeneration':None, 'hp_regeneration_percentage':None, 'mana_regeneration':None, 'mana_regeneration_percentage':None, 'attack_speed':None, 'attack_speed_percentage':None, 'evasion':None, 'evasion_percentage':None, 'movement_speed':None, 'movement_speed_percentage':None, 'cooldown':None, 'mana_cost':None, 'tier':1, 'parent_id':None, 'description':None, 'active':None, 'passive':None, 'use':None, 'sub_description':None},
            {'name':, 'vendor':, 'cost':, 'image_name':, 'resource_name':, 'hon_name':, 'order':, 'agility':None, 'strength':None, 'intelligence':None, 'all':None, 'armor':None, 'damage':None, 'selected_attribute':None, 'mana':None, 'health':None, 'hp_regeneration':None, 'hp_regeneration_percentage':None, 'mana_regeneration':None, 'mana_regeneration_percentage':None, 'attack_speed':None, 'attack_speed_percentage':None, 'evasion':None, 'evasion_percentage':None, 'movement_speed':None, 'movement_speed_percentage':None, 'cooldown':None, 'mana_cost':None, 'tier':1, 'parent_id':None, 'description':None, 'active':None, 'passive':None, 'use':None, 'sub_description':None},
            {'name':, 'vendor':, 'cost':, 'image_name':, 'resource_name':, 'hon_name':, 'order':, 'agility':None, 'strength':None, 'intelligence':None, 'all':None, 'armor':None, 'damage':None, 'selected_attribute':None, 'mana':None, 'health':None, 'hp_regeneration':None, 'hp_regeneration_percentage':None, 'mana_regeneration':None, 'mana_regeneration_percentage':None, 'attack_speed':None, 'attack_speed_percentage':None, 'evasion':None, 'evasion_percentage':None, 'movement_speed':None, 'movement_speed_percentage':None, 'cooldown':None, 'mana_cost':None, 'tier':1, 'parent_id':None, 'description':None, 'active':None, 'passive':None, 'use':None, 'sub_description':None},
            {'name':, 'vendor':, 'cost':, 'image_name':, 'resource_name':, 'hon_name':, 'order':, 'agility':None, 'strength':None, 'intelligence':None, 'all':None, 'armor':None, 'damage':None, 'selected_attribute':None, 'mana':None, 'health':None, 'hp_regeneration':None, 'hp_regeneration_percentage':None, 'mana_regeneration':None, 'mana_regeneration_percentage':None, 'attack_speed':None, 'attack_speed_percentage':None, 'evasion':None, 'evasion_percentage':None, 'movement_speed':None, 'movement_speed_percentage':None, 'cooldown':None, 'mana_cost':None, 'tier':1, 'parent_id':None, 'description':None, 'active':None, 'passive':None, 'use':None, 'sub_description':None},
            {'name':, 'vendor':, 'cost':, 'image_name':, 'resource_name':, 'hon_name':, 'order':, 'agility':None, 'strength':None, 'intelligence':None, 'all':None, 'armor':None, 'damage':None, 'selected_attribute':None, 'mana':None, 'health':None, 'hp_regeneration':None, 'hp_regeneration_percentage':None, 'mana_regeneration':None, 'mana_regeneration_percentage':None, 'attack_speed':None, 'attack_speed_percentage':None, 'evasion':None, 'evasion_percentage':None, 'movement_speed':None, 'movement_speed_percentage':None, 'cooldown':None, 'mana_cost':None, 'tier':1, 'parent_id':None, 'description':None, 'active':None, 'passive':None, 'use':None, 'sub_description':None},
            {'name':, 'vendor':, 'cost':, 'image_name':, 'resource_name':, 'hon_name':, 'order':, 'agility':None, 'strength':None, 'intelligence':None, 'all':None, 'armor':None, 'damage':None, 'selected_attribute':None, 'mana':None, 'health':None, 'hp_regeneration':None, 'hp_regeneration_percentage':None, 'mana_regeneration':None, 'mana_regeneration_percentage':None, 'attack_speed':None, 'attack_speed_percentage':None, 'evasion':None, 'evasion_percentage':None, 'movement_speed':None, 'movement_speed_percentage':None, 'cooldown':None, 'mana_cost':None, 'tier':1, 'parent_id':None, 'description':None, 'active':None, 'passive':None, 'use':None, 'sub_description':None},
            {'name':, 'vendor':, 'cost':, 'image_name':, 'resource_name':, 'hon_name':, 'order':, 'agility':None, 'strength':None, 'intelligence':None, 'all':None, 'armor':None, 'damage':None, 'selected_attribute':None, 'mana':None, 'health':None, 'hp_regeneration':None, 'hp_regeneration_percentage':None, 'mana_regeneration':None, 'mana_regeneration_percentage':None, 'attack_speed':None, 'attack_speed_percentage':None, 'evasion':None, 'evasion_percentage':None, 'movement_speed':None, 'movement_speed_percentage':None, 'cooldown':None, 'mana_cost':None, 'tier':1, 'parent_id':None, 'description':None, 'active':None, 'passive':None, 'use':None, 'sub_description':None},
            {'name':, 'vendor':, 'cost':, 'image_name':, 'resource_name':, 'hon_name':, 'order':, 'agility':None, 'strength':None, 'intelligence':None, 'all':None, 'armor':None, 'damage':None, 'selected_attribute':None, 'mana':None, 'health':None, 'hp_regeneration':None, 'hp_regeneration_percentage':None, 'mana_regeneration':None, 'mana_regeneration_percentage':None, 'attack_speed':None, 'attack_speed_percentage':None, 'evasion':None, 'evasion_percentage':None, 'movement_speed':None, 'movement_speed_percentage':None, 'cooldown':None, 'mana_cost':None, 'tier':1, 'parent_id':None, 'description':None, 'active':None, 'passive':None, 'use':None, 'sub_description':None},
            {'name':, 'vendor':, 'cost':, 'image_name':, 'resource_name':, 'hon_name':, 'order':, 'agility':None, 'strength':None, 'intelligence':None, 'all':None, 'armor':None, 'damage':None, 'selected_attribute':None, 'mana':None, 'health':None, 'hp_regeneration':None, 'hp_regeneration_percentage':None, 'mana_regeneration':None, 'mana_regeneration_percentage':None, 'attack_speed':None, 'attack_speed_percentage':None, 'evasion':None, 'evasion_percentage':None, 'movement_speed':None, 'movement_speed_percentage':None, 'cooldown':None, 'mana_cost':None, 'tier':1, 'parent_id':None, 'description':None, 'active':None, 'passive':None, 'use':None, 'sub_description':None},
            {'name':, 'vendor':, 'cost':, 'image_name':, 'resource_name':, 'hon_name':, 'order':, 'agility':None, 'strength':None, 'intelligence':None, 'all':None, 'armor':None, 'damage':None, 'selected_attribute':None, 'mana':None, 'health':None, 'hp_regeneration':None, 'hp_regeneration_percentage':None, 'mana_regeneration':None, 'mana_regeneration_percentage':None, 'attack_speed':None, 'attack_speed_percentage':None, 'evasion':None, 'evasion_percentage':None, 'movement_speed':None, 'movement_speed_percentage':None, 'cooldown':None, 'mana_cost':None, 'tier':1, 'parent_id':None, 'description':None, 'active':None, 'passive':None, 'use':None, 'sub_description':None},
            {'name':, 'vendor':, 'cost':, 'image_name':, 'resource_name':, 'hon_name':, 'order':, 'agility':None, 'strength':None, 'intelligence':None, 'all':None, 'armor':None, 'damage':None, 'selected_attribute':None, 'mana':None, 'health':None, 'hp_regeneration':None, 'hp_regeneration_percentage':None, 'mana_regeneration':None, 'mana_regeneration_percentage':None, 'attack_speed':None, 'attack_speed_percentage':None, 'evasion':None, 'evasion_percentage':None, 'movement_speed':None, 'movement_speed_percentage':None, 'cooldown':None, 'mana_cost':None, 'tier':1, 'parent_id':None, 'description':None, 'active':None, 'passive':None, 'use':None, 'sub_description':None},
            {'name':, 'vendor':, 'cost':, 'image_name':, 'resource_name':, 'hon_name':, 'order':, 'agility':None, 'strength':None, 'intelligence':None, 'all':None, 'armor':None, 'damage':None, 'selected_attribute':None, 'mana':None, 'health':None, 'hp_regeneration':None, 'hp_regeneration_percentage':None, 'mana_regeneration':None, 'mana_regeneration_percentage':None, 'attack_speed':None, 'attack_speed_percentage':None, 'evasion':None, 'evasion_percentage':None, 'movement_speed':None, 'movement_speed_percentage':None, 'cooldown':None, 'mana_cost':None, 'tier':1, 'parent_id':None, 'description':None, 'active':None, 'passive':None, 'use':None, 'sub_description':None},
            {'name':, 'vendor':, 'cost':, 'image_name':, 'resource_name':, 'hon_name':, 'order':, 'agility':None, 'strength':None, 'intelligence':None, 'all':None, 'armor':None, 'damage':None, 'selected_attribute':None, 'mana':None, 'health':None, 'hp_regeneration':None, 'hp_regeneration_percentage':None, 'mana_regeneration':None, 'mana_regeneration_percentage':None, 'attack_speed':None, 'attack_speed_percentage':None, 'evasion':None, 'evasion_percentage':None, 'movement_speed':None, 'movement_speed_percentage':None, 'cooldown':None, 'mana_cost':None, 'tier':1, 'parent_id':None, 'description':None, 'active':None, 'passive':None, 'use':None, 'sub_description':None},
            {'name':, 'vendor':, 'cost':, 'image_name':, 'resource_name':, 'hon_name':, 'order':, 'agility':None, 'strength':None, 'intelligence':None, 'all':None, 'armor':None, 'damage':None, 'selected_attribute':None, 'mana':None, 'health':None, 'hp_regeneration':None, 'hp_regeneration_percentage':None, 'mana_regeneration':None, 'mana_regeneration_percentage':None, 'attack_speed':None, 'attack_speed_percentage':None, 'evasion':None, 'evasion_percentage':None, 'movement_speed':None, 'movement_speed_percentage':None, 'cooldown':None, 'mana_cost':None, 'tier':1, 'parent_id':None, 'description':None, 'active':None, 'passive':None, 'use':None, 'sub_description':None},
            {'name':, 'vendor':, 'cost':, 'image_name':, 'resource_name':, 'hon_name':, 'order':, 'agility':None, 'strength':None, 'intelligence':None, 'all':None, 'armor':None, 'damage':None, 'selected_attribute':None, 'mana':None, 'health':None, 'hp_regeneration':None, 'hp_regeneration_percentage':None, 'mana_regeneration':None, 'mana_regeneration_percentage':None, 'attack_speed':None, 'attack_speed_percentage':None, 'evasion':None, 'evasion_percentage':None, 'movement_speed':None, 'movement_speed_percentage':None, 'cooldown':None, 'mana_cost':None, 'tier':1, 'parent_id':None, 'description':None, 'active':None, 'passive':None, 'use':None, 'sub_description':None},
            {'name':, 'vendor':, 'cost':, 'image_name':, 'resource_name':, 'hon_name':, 'order':, 'agility':None, 'strength':None, 'intelligence':None, 'all':None, 'armor':None, 'damage':None, 'selected_attribute':None, 'mana':None, 'health':None, 'hp_regeneration':None, 'hp_regeneration_percentage':None, 'mana_regeneration':None, 'mana_regeneration_percentage':None, 'attack_speed':None, 'attack_speed_percentage':None, 'evasion':None, 'evasion_percentage':None, 'movement_speed':None, 'movement_speed_percentage':None, 'cooldown':None, 'mana_cost':None, 'tier':1, 'parent_id':None, 'description':None, 'active':None, 'passive':None, 'use':None, 'sub_description':None},
            {'name':, 'vendor':, 'cost':, 'image_name':, 'resource_name':, 'hon_name':, 'order':, 'agility':None, 'strength':None, 'intelligence':None, 'all':None, 'armor':None, 'damage':None, 'selected_attribute':None, 'mana':None, 'health':None, 'hp_regeneration':None, 'hp_regeneration_percentage':None, 'mana_regeneration':None, 'mana_regeneration_percentage':None, 'attack_speed':None, 'attack_speed_percentage':None, 'evasion':None, 'evasion_percentage':None, 'movement_speed':None, 'movement_speed_percentage':None, 'cooldown':None, 'mana_cost':None, 'tier':1, 'parent_id':None, 'description':None, 'active':None, 'passive':None, 'use':None, 'sub_description':None},
            {'name':, 'vendor':, 'cost':, 'image_name':, 'resource_name':, 'hon_name':, 'order':, 'agility':None, 'strength':None, 'intelligence':None, 'all':None, 'armor':None, 'damage':None, 'selected_attribute':None, 'mana':None, 'health':None, 'hp_regeneration':None, 'hp_regeneration_percentage':None, 'mana_regeneration':None, 'mana_regeneration_percentage':None, 'attack_speed':None, 'attack_speed_percentage':None, 'evasion':None, 'evasion_percentage':None, 'movement_speed':None, 'movement_speed_percentage':None, 'cooldown':None, 'mana_cost':None, 'tier':1, 'parent_id':None, 'description':None, 'active':None, 'passive':None, 'use':None, 'sub_description':None},
            {'name':, 'vendor':, 'cost':, 'image_name':, 'resource_name':, 'hon_name':, 'order':, 'agility':None, 'strength':None, 'intelligence':None, 'all':None, 'armor':None, 'damage':None, 'selected_attribute':None, 'mana':None, 'health':None, 'hp_regeneration':None, 'hp_regeneration_percentage':None, 'mana_regeneration':None, 'mana_regeneration_percentage':None, 'attack_speed':None, 'attack_speed_percentage':None, 'evasion':None, 'evasion_percentage':None, 'movement_speed':None, 'movement_speed_percentage':None, 'cooldown':None, 'mana_cost':None, 'tier':1, 'parent_id':None, 'description':None, 'active':None, 'passive':None, 'use':None, 'sub_description':None},
            {'name':, 'vendor':, 'cost':, 'image_name':, 'resource_name':, 'hon_name':, 'order':, 'agility':None, 'strength':None, 'intelligence':None, 'all':None, 'armor':None, 'damage':None, 'selected_attribute':None, 'mana':None, 'health':None, 'hp_regeneration':None, 'hp_regeneration_percentage':None, 'mana_regeneration':None, 'mana_regeneration_percentage':None, 'attack_speed':None, 'attack_speed_percentage':None, 'evasion':None, 'evasion_percentage':None, 'movement_speed':None, 'movement_speed_percentage':None, 'cooldown':None, 'mana_cost':None, 'tier':1, 'parent_id':None, 'description':None, 'active':None, 'passive':None, 'use':None, 'sub_description':None},
            {'name':, 'vendor':, 'cost':, 'image_name':, 'resource_name':, 'hon_name':, 'order':, 'agility':None, 'strength':None, 'intelligence':None, 'all':None, 'armor':None, 'damage':None, 'selected_attribute':None, 'mana':None, 'health':None, 'hp_regeneration':None, 'hp_regeneration_percentage':None, 'mana_regeneration':None, 'mana_regeneration_percentage':None, 'attack_speed':None, 'attack_speed_percentage':None, 'evasion':None, 'evasion_percentage':None, 'movement_speed':None, 'movement_speed_percentage':None, 'cooldown':None, 'mana_cost':None, 'tier':1, 'parent_id':None, 'description':None, 'active':None, 'passive':None, 'use':None, 'sub_description':None}
        ]
    )

    # Base Heroes
    op.bulk_insert('heroes',
        [
            {'name':, 'description':, 'image_name':, 'default_filename':, 'faction':, 'stat':, 'roles':, 'strength':, 'agility':, 'intelligence':, 'strength_gain':, 'agility_gain':, 'intelligence_gain':, 'min_hp':, 'max_hp':, 'min_mana':, 'max_mana':, 'min_damage':, 'max_damage':, 'armor':, 'movepeed':, 'attack_range':, 'min_attack_animation':, 'max_attack_animation':, 'min_cast_animation':, 'max_cast_animation':, 'base_attack_time':, 'missile_speed':, 'day_site_range':, 'night_site_range':, 'resource_name':, 'order':},
        ]
    )

    # Base Skills
    op.bulk_insert('skills',
        [
            {'name':, 'image_name':, 'description':, 'cooldown':, 'mana_cost':, 'ability_type':, 'targeting_type':, 'allowed_targets':, 'level':, 'damage_type':, 'parent_id':, 'hero_id':},
        ]
    )

    # Base Item Recipes
    op.bulk_insert('items_items',
        [
            {'builds_id':, 'requires_id':},
        ]
    )

def downgrade():
    pass
